[package]
name = "ex_monty"
version = "0.1.0"
edition = "2021"
rust-version = "1.90"

[lib]
name = "ex_monty"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37", features = ["big_integer"] }
monty = { git = "https://github.com/pydantic/monty.git", rev = "45a3b2d57e6ce723fed4166fb032242ece74a663" }
# monty = { path = "../../../monty/crates/monty" }
num-bigint = "0.4"
postcard = { version = "1.1", features = ["alloc"] }

serde = { version = "1.0", features = ["derive"] }
